### ISSUE TITLE
demo is not working anymore

### ISSUE THREAD

**Issue by molekilla** [fido-alliance/webauthn-demo#2]
Hi,

It returns "Error: Server responed with error. The message is: Can not authenticate signature!" when registering an account. Tested with Firefox Nightly 61 and Chrome Version 67.0.3395.0 (Developer Build) custom (64-bit)

**Comment by herrjemand** [comment]
@molekilla Thanks for reporting that. I have fixed missing parameter, so it should work now

Regards. Yuriy

**Comment by chongns-sains** [comment]
Hi, there is a regression. Works on Firefox 62 but not Chrome 69.0.3497.81 (Official Build). Same error.
Please help
