### ISSUE TITLE
Chrome show 'NotAllowedError' because the page does not have focus.

### ISSUE THREAD

**Issue by HWataru** [fido-alliance/webauthn-demo#3]
### My Environment
* Windows 10
* Chrome Version 67.0.3396.10 (Official Build) dev (64-bit)

### issue
When I register new account, Chrome show message 

```
http://localhost:3000 want to
 see the make and model of your security key
```

after click "Allow" button, chrome show error below and don't return registration response.

`NotAllowedError: The operation is not allowed at this time because the page does not have focus.`

**Comment by agl** [comment]
This is a Chrome bug where, on Windows, the popup takes focus. The fix is already in the works.

**Comment by herrjemand** [comment]
Thanks for confirming @agl 

Closing it then *)

**Comment by HWataru** [comment]
It seems that Chrome has been fixed. It works on Chrome version 68.0.342.0 on Windows 10 :)
