### ISSUE TITLE
Can not authenticate signature!

### ISSUE THREAD

**Issue by laopisai** [fido-alliance/webauthn-demo#6]
I just realise I cannot reopen issue #2

there is a regression. Works on Firefox 62 but not Chrome 69.0.3497.81 (Official Build). Same error, "Can not authenticate signature!"

Please help

_Originally posted by @chongns-sains in https://github.com/fido-alliance/webauthn-demo/issues/2#issuecomment-427277517_

**Comment by herrjemand** [comment]
@chongns-sains Are you using built in authenticator?

**Comment by laopisai** [comment]
HI, please review https://github.com/fido-alliance/webauthn-demo/pull/7

I think the 'packed' format solve this issue

**Comment by herrjemand** [comment]
@laopisai Thanks for your solutions. Here is another way you can do it https://medium.com/@herrjemand/verifying-fido2-packed-attestation-a067a9b2facd (If you are curious)

Here is more in depth https://medium.com/@herrjemand/verifying-fido2-responses-4691288c8770

Thanks for you work.
