### ISSUE TITLE
Not working at all ?

### ISSUE THREAD

**Issue by matthiasg** [fido-alliance/webauthn-demo#9]
I tried this on Node 10 , Chrome 72 and latest Firefox. Installs fine and shows login and register page, but nothing happens other than switching back and forth between these pages.. The Go demo at https://github.com/duo-labs/webauthn.io works fine with all browsers.

All network requests return status code 200  but webnauth.js for example is basically empty ? What is supposed to happen here?

**Comment by herrjemand** [comment]
@matthiasg You probably looking for Completed-Demo branch https://github.com/fido-alliance/webauthn-demo/tree/completed-demo

This part of the Workshop https://slides.com/fidoalliance/jan-2018-fido-seminar-webauthn-tutorial#/

**Comment by matthiasg** [comment]
@herrjemand will look into that then. Quite confusing though since webauthn.io directly links to this project without mentioning to go to another branch as far as I saw.

**Comment by herrjemand** [comment]
@matthiasg Sorry. I have added clarification in the title.
